import { expect,test } from '@playwright/test'
import { join } from 'node:path'

test('team turns a factory catalog into a selected market direction',async({page})=>{
  await page.goto('/login')
  await page.getByLabel('邮箱').fill('admin@example.com')
  await page.getByLabel('密码').fill('ChangeMe-Local-Only-123!')
  await page.getByRole('button',{name:'登录'}).click()
  await page.getByRole('link',{name:'SINOFORM 齿轮工厂'}).click()
  await page.getByRole('link',{name:'资料与能力画像'}).click()
  await page.setInputFiles('input[type=file]',join(import.meta.dirname,'fixtures','gear-catalog.txt'))
  await page.getByRole('button',{name:'上传资料'}).click()
  await expect(page.getByText('gear-catalog.txt')).toBeVisible()
  await page.getByRole('button',{name:'开始 AI 提取'}).click()
  await expect(page.getByText('提取完成')).toBeVisible({timeout:15_000})
  await page.getByRole('link',{name:'审核能力画像'}).click()
  await expect(page.getByText('待审核')).toBeVisible()
  await page.getByRole('button',{name:'确认能力'}).first().click()
  await page.getByLabel('确认依据').fill('工厂负责人访谈确认')
  await page.getByRole('button',{name:'保存审核'}).click()
  await expect(page.getByText('已确认')).toBeVisible()
  await page.getByRole('link',{name:'选品与市场'}).click()
  await page.getByRole('button',{name:'生成候选方向'}).click()
  await page.getByRole('button',{name:'添加市场证据'}).first().click()
  await page.getByLabel('证据标题').fill('包装设备齿轮采购需求记录')
  await page.getByLabel('来源网址').fill('https://example.com/verified-market-note')
  await page.getByLabel('证据摘要').fill('团队人工审核的市场访谈记录公开摘要')
  await page.getByRole('button',{name:'保存证据'}).click()
  await expect(page.getByText('已有人工证据').first()).toBeVisible()
  await page.getByRole('button',{name:'设为主验证方向'}).first().click()
  await expect(page.getByText('主验证方向',{exact:true})).toBeVisible()
})
