import { randomUUID } from 'node:crypto'
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify'
import { z } from 'zod'
import { marketGenerationSchema } from '@workbench/contracts'
import { sessionCookieName } from '../auth/session.js'
import type { AppDatabase } from '../db/database.js'
import type { MarketGenerator } from '../ai/marketGenerator.js'
import type { AuthService, AuthenticatedUser } from './auth.js'
import type { ProjectRepository } from './projects.js'

export class SqliteMarketRepository {
  constructor(private readonly db: AppDatabase) {}
  async confirmedCapabilities(projectId:string){return this.db.prepare(`SELECT c.id,c.category,c.name,c.value,c.evidence_quote AS evidenceQuote FROM capabilities c WHERE c.project_id=? AND c.review_status='CONFIRMED' AND NOT EXISTS(SELECT 1 FROM capabilities n WHERE n.supersedes_capability_id=c.id)`).all(projectId) as Array<{id:string;category:string;name:string;value:string;evidenceQuote:string}>}
  projectContext(projectId:string){const p=this.db.prepare(`SELECT name,legal_name,export_stage FROM factory_projects WHERE id=?`).get(projectId) as {name:string;legal_name:string;export_stage:string};return `${p.name}；${p.legal_name}；外贸阶段 ${p.export_stage}`}
  async saveGenerated(projectId:string,output:ReturnType<typeof marketGenerationSchema.parse>,model:string){const now=new Date().toISOString();this.db.exec('BEGIN IMMEDIATE');try{for(const c of output.candidates)this.db.prepare(`INSERT INTO market_candidates (id,project_id,product_focus,region,customer_type,rationale,capability_ids_json,uncertainties_json,questions_json,scores_json,verification_status,status,created_at,updated_at,generated_model,prompt_version) VALUES (?,?,?,?,?,?,?,?,?,?,'UNVERIFIED','DRAFT',?,?,?,?)`).run(randomUUID(),projectId,c.productFocus,c.region,c.customerType,c.rationale,JSON.stringify(c.capabilityIds),JSON.stringify(c.uncertainties),JSON.stringify(c.interviewQuestions),JSON.stringify(c.scores),now,now,model,'market-v1');this.db.exec('COMMIT')}catch(e){this.db.exec('ROLLBACK');throw e}}
  private evidence(candidateId:string){return this.db.prepare(`SELECT e.id,e.title,e.url,e.source_type AS sourceType,e.published_at AS publishedAt,e.summary,e.supports_or_challenges AS supportsOrChallenges,e.created_at AS createdAt,u.display_name AS reviewerName FROM market_evidence e JOIN users u ON u.id=e.reviewer_id WHERE e.candidate_id=? ORDER BY e.created_at DESC`).all(candidateId)}
  async list(projectId:string){const rows=this.db.prepare(`SELECT * FROM market_candidates WHERE project_id=? ORDER BY created_at DESC`).all(projectId) as Array<Record<string,unknown>>;const capRows=this.db.prepare(`SELECT id,name FROM capabilities WHERE project_id=?`).all(projectId) as Array<{id:string;name:string}>;const names=new Map(capRows.map(x=>[x.id,x.name]));const items=rows.map(r=>{const ids=JSON.parse(r.capability_ids_json as string) as string[];const evidence=this.evidence(r.id as string);return{id:r.id,productFocus:r.product_focus,region:r.region,customerType:r.customer_type,rationale:r.rationale,capabilities:ids.map(id=>({id,name:names.get(id)??id})),uncertainties:JSON.parse(r.uncertainties_json as string),interviewQuestions:JSON.parse(r.questions_json as string),scores:JSON.parse(r.scores_json as string),verificationStatus:evidence.length?'EVIDENCE_ADDED':'UNVERIFIED',status:r.status,evidence}});const decision=this.db.prepare(`SELECT id,primary_candidate_id AS primaryCandidateId,backup_candidate_id AS backupCandidateId,reason,created_at AS createdAt FROM market_decisions d WHERE project_id=? AND NOT EXISTS(SELECT 1 FROM market_decisions n WHERE n.supersedes_decision_id=d.id) ORDER BY created_at DESC LIMIT 1`).get(projectId)??null;return{items,decision}}
  async addEvidence(projectId:string,candidateId:string,input:{title:string;url:string;sourceType:string;publishedAt?:string;summary:string;supportsOrChallenges:string},actor:AuthenticatedUser){if(!this.db.prepare(`SELECT 1 FROM market_candidates WHERE project_id=? AND id=?`).get(projectId,candidateId))return null;const id=randomUUID(),now=new Date().toISOString();this.db.prepare(`INSERT INTO market_evidence (id,project_id,candidate_id,reviewer_id,title,url,source_type,published_at,summary,supports_or_challenges,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,candidateId,actor.id,input.title,input.url,input.sourceType,input.publishedAt??null,input.summary,input.supportsOrChallenges,now);return{id,...input,reviewedBy:actor.id,createdAt:now}}
  async decide(projectId:string,input:{primaryCandidateId:string;backupCandidateId?:string|null;reason:string},actor:AuthenticatedUser){if(input.backupCandidateId===input.primaryCandidateId)return{error:'BACKUP_MUST_DIFFER'} as const;const ids=[input.primaryCandidateId,...(input.backupCandidateId?[input.backupCandidateId]:[])];for(const id of ids){const row=this.db.prepare(`SELECT capability_ids_json,(SELECT COUNT(*) FROM market_evidence e WHERE e.candidate_id=c.id) AS evidence_count FROM market_candidates c WHERE c.project_id=? AND c.id=?`).get(projectId,id) as {capability_ids_json:string;evidence_count:number}|undefined;if(!row||JSON.parse(row.capability_ids_json).length===0||row.evidence_count<1)return{error:'MARKET_EVIDENCE_REQUIRED'} as const}const previous=this.db.prepare(`SELECT id FROM market_decisions d WHERE project_id=? AND NOT EXISTS(SELECT 1 FROM market_decisions n WHERE n.supersedes_decision_id=d.id) ORDER BY created_at DESC LIMIT 1`).get(projectId) as {id:string}|undefined;const id=randomUUID(),now=new Date().toISOString();this.db.exec('BEGIN IMMEDIATE');try{this.db.prepare(`INSERT INTO market_decisions (id,project_id,primary_candidate_id,backup_candidate_id,reason,author_id,supersedes_decision_id,created_at) VALUES (?,?,?,?,?,?,?,?)`).run(id,projectId,input.primaryCandidateId,input.backupCandidateId??null,input.reason,actor.id,previous?.id??null,now);this.db.prepare(`INSERT INTO audit_events (id,project_id,actor_id,action,entity_type,entity_id,changed_fields_json,created_at) VALUES (?,?,?,'SELECT_MARKET','MarketDecision',?,?,?)`).run(randomUUID(),projectId,actor.id,id,JSON.stringify(['primaryCandidateId','backupCandidateId','reason']),now);this.db.exec('COMMIT')}catch(e){this.db.exec('ROLLBACK');throw e}return{id,...input,authorId:actor.id,createdAt:now}}
}

export async function generateMarkets(projectId:string,deps:{repository:SqliteMarketRepository;generator:MarketGenerator;model:string}){const capabilities=await deps.repository.confirmedCapabilities(projectId);if(!capabilities.length)throw new Error('NO_CONFIRMED_CAPABILITIES');const output=marketGenerationSchema.parse(await deps.generator.generate({projectContext:deps.repository.projectContext(projectId),capabilities}));await deps.repository.saveGenerated(projectId,output,deps.model);return deps.repository.list(projectId)}

async function actor(request:FastifyRequest,reply:FastifyReply,auth:AuthService){const token=request.cookies[sessionCookieName];const u=token?await auth.getUserByRawToken(token):null;if(!u){reply.code(401).send({code:'UNAUTHENTICATED',message:'请先登录'});return null}return u}
const evidenceSchema=z.object({title:z.string().trim().min(1),url:z.url().refine(v=>v.startsWith('https://'),'必须使用 HTTPS 链接'),sourceType:z.string().trim().min(1),publishedAt:z.iso.date().optional(),summary:z.string().trim().min(1),supportsOrChallenges:z.string().trim().min(1)})
const decisionSchema=z.object({primaryCandidateId:z.string().min(1),backupCandidateId:z.string().nullable().optional(),reason:z.string().trim().min(1)})

export async function registerMarketRoutes(app:FastifyInstance,auth:AuthService,projects:ProjectRepository,repository:SqliteMarketRepository,generator:MarketGenerator,model:string){
  app.get<{Params:{projectId:string}}>('/projects/:projectId/market-candidates',async(req,reply)=>{const u=await actor(req,reply,auth);if(!u)return;const p=await projects.getForUser(req.params.projectId,u);if(!p)return reply.code(404).send({code:'PROJECT_NOT_FOUND',message:'项目不存在'});return{...(await repository.list(p.id)),membershipRole:p.membershipRole}})
  app.post<{Params:{projectId:string}}>('/projects/:projectId/market-candidates/generate',async(req,reply)=>{const u=await actor(req,reply,auth);if(!u)return;const p=await projects.getForUser(req.params.projectId,u);if(!p)return reply.code(404).send({code:'PROJECT_NOT_FOUND',message:'项目不存在'});if(p.membershipRole==='VIEWER')return reply.code(403).send({code:'FORBIDDEN',message:'只读成员不能生成候选'});try{return reply.code(201).send(await generateMarkets(p.id,{repository,generator,model}))}catch(e){if((e as Error).message==='NO_CONFIRMED_CAPABILITIES')return reply.code(422).send({code:'CONFIRMED_CAPABILITY_REQUIRED',message:'请先确认至少一项工厂能力'});throw e}})
  app.post<{Params:{projectId:string;candidateId:string}}>('/projects/:projectId/market-candidates/:candidateId/evidence',async(req,reply)=>{const u=await actor(req,reply,auth);if(!u)return;const p=await projects.getForUser(req.params.projectId,u);if(!p)return reply.code(404).send({code:'PROJECT_NOT_FOUND',message:'项目不存在'});if(p.membershipRole==='VIEWER')return reply.code(403).send({code:'FORBIDDEN',message:'只读成员不能添加证据'});const parsed=evidenceSchema.safeParse(req.body);if(!parsed.success)return reply.code(422).send({code:'VALIDATION_ERROR',message:'请完整填写 HTTPS 市场证据'});const result=await repository.addEvidence(p.id,req.params.candidateId,parsed.data,u);return result?reply.code(201).send(result):reply.code(404).send({code:'CANDIDATE_NOT_FOUND',message:'候选方向不存在'})})
  app.post<{Params:{projectId:string}}>('/projects/:projectId/market-decisions',async(req,reply)=>{const u=await actor(req,reply,auth);if(!u)return;const p=await projects.getForUser(req.params.projectId,u);if(!p)return reply.code(404).send({code:'PROJECT_NOT_FOUND',message:'项目不存在'});if(p.membershipRole==='VIEWER')return reply.code(403).send({code:'FORBIDDEN',message:'只读成员不能选择方向'});const parsed=decisionSchema.safeParse(req.body);if(!parsed.success)return reply.code(422).send({code:'VALIDATION_ERROR',message:'请填写选择理由'});const result=await repository.decide(p.id,parsed.data,u);if('error'in result)return reply.code(422).send({code:result.error,message:result.error==='MARKET_EVIDENCE_REQUIRED'?'主备方向都必须至少有一条人工市场证据':'备用方向不能与主方向相同'});return reply.code(201).send(result)})
}
